### PR TITLE
[Draft] Add upgrade lock file and healthcheck to the container

### LINKED ISSUE #59: Healthcheck could break update
i run this image in a swarm cluster that checks for health and if the container is unhealthy it restarts the container and try to get it running. this will happn in the upgrade process which dont work. 

i used 
```
healthcheck:
    test: [CMD-SHELL, "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    start_period: 20s
    interval: 30s
    retries: 5
    timeout: 5s
```

i think nothing we can do about directly (maybee providing a script that does this healthcheck but will also exit code 0 when an update is running?) but more a think we should mention?

### PR DESCRIPTION
**Pull request by wuast94**
Should fix #59 

dont have time to test it but should work.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome!  I'll take a look at this over the next few days.

CI seems to be failing atm, but it probably won't be hard to get things working the way we want. :smile:

**Comment by wuast94** [comment]
good catch, i changed the script name and missed this

**Comment by justinclift** [comment]
Interestingly, it looks like the CI checks aren't functional when the PR is created in a different repo.  I'll re-create this PR with the commits in branch of our repo, so we can see the actual CI check results. :smile:

**Comment by justinclift** [comment]
Actually, lets close this PR and continue the development in #63.  If changes do need to be made, then we'll need to do them in that PR anyway. :smile:

**Pull request closed without merging**
