### PR TITLE
Update README.md to mention healthcheck

### PR DESCRIPTION
**Pull request by wuast94**
in respect to https://github.com/pgautoupgrade/docker-pgautoupgrade/issues/59#issuecomment-2440948571

### CODE REVIEW

**Comment by justinclift** [comment]
Oh.  I was thinking (mistakenly?) that we should be telling people to use the health check script we provide rather than something like `pg_isready`.

Maybe I need more coffee? :smile:

**Comment by wuast94** [comment]
> Oh. I was thinking (mistakenly?) that we should be telling people to use the health check script we provide rather than something like `pg_isready`.
> 
> Maybe I need more coffee? 😄

I take one too :P 

basicly i added the healthcheck script to the dockerfiles, so the containers have our healthchek build in, no need to declair it. 
the reason we mention this in the readme is so that people remove any healthcheck they made or at least give them an intensensive too check what we do becouse if they declaire it the compose or so they would override the built in one

**Comment by wuast94** [comment]
https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/57fa939d7e5108b7bdb3bb354ec9de2f4e6bd234/Dockerfile.alpine#L190

https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/57fa939d7e5108b7bdb3bb354ec9de2f4e6bd234/Dockerfile.bookworm#L185

here we alrady bake it in the docker container.

**Comment by justinclift** [comment]
Merging this finally.  Sorry for taking so long to get to it. 😇

**Pull request merged**
